# Generated by Django 4.2.7 on 2023-12-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_product_productowner_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/7130/7130776.png'),
        ),
    ]
