# Generated by Django 4.2.7 on 2023-12-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comments_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='product',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='product',
        ),
    ]
